pragma SPARK_Mode (On);

with GlobaleDatentypen;

with DatenbankRecords;

package RassenDatenbank is

   type RassenListeArray is array (GlobaleDatentypen.Rassen_Verwendet_Enum'Range) of DatenbankRecords.RassenListeRecord;
   RassenListe : RassenListeArray := (
                                      GlobaleDatentypen.Menschen =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Demokratie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Maschinen =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Biber =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Wölfe =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Fischotter =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Marderhund =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Wildschwein =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Waschbär =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Maulwurf =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Ziesel =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Spinnen =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Steinbock =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Greifvögel =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Fische =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Schlangen =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Salamander =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Pflanzen =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Igel =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie))
                                     );
   
   procedure StandardRassenDatenbankLaden;
   
private
   
   RassenListeStandard : constant RassenListeArray := (
                                                       GlobaleDatentypen.Menschen =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Demokratie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Maschinen =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Biber =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Wölfe =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Fischotter =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Marderhund =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Wildschwein =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Waschbär =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Maulwurf =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Ziesel =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Spinnen =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Steinbock =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Greifvögel =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Fische =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Schlangen =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Salamander =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Pflanzen =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Igel =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie))
                                                      );

end RassenDatenbank;
