pragma SPARK_Mode (On);

with GlobaleDatentypen;

with DatenbankRecords;

package RassenDatenbank is

   type RassenListeArray is array (GlobaleDatentypen.Rassen_Verwendet_Enum'Range) of DatenbankRecords.RassenListeRecord;
   RassenListe : RassenListeArray := (
                                      GlobaleDatentypen.Rasse_1 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Demokratie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_2 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_3 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_4 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_5 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_6 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_7 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_8 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_9 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_10 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_11 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_12 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_13 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_14 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_15 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_16 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_17 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie)),
                                      
                                      GlobaleDatentypen.Rasse_18 =>
                                        (Aggressivität       => 0,
                                         Expansion           => 0,
                                         Wissenschaft        => 0,
                                         Produktion          => 0,
                                         Wirtschaft          => 0,
                                         Bewirtschaftung     => 0,
                                         GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie,
                                                                  GlobaleDatentypen.Anarchie))
                                     );
   
   procedure StandardRassenDatenbankWiederherstellen;
   
private
   
   RassenListeStandard : constant RassenListeArray := (
                                                       GlobaleDatentypen.Rasse_1 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_2 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_3 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_4 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_5 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_6 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_7 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_8 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_9 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_10 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_11 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_12 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_13 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_14 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_15 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_16 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_17 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie)),
                                      
                                                       GlobaleDatentypen.Rasse_18 =>
                                                         (Aggressivität       => 0,
                                                          Expansion           => 0,
                                                          Wissenschaft        => 0,
                                                          Produktion          => 0,
                                                          Wirtschaft          => 0,
                                                          Bewirtschaftung     => 0,
                                                          GültigeStaatsformen => (GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie,
                                                                                   GlobaleDatentypen.Anarchie))
                                                      );

end RassenDatenbank;
