pragma SPARK_Mode (On);
pragma Warnings (Off, "*array aggregate*");

with RassenDatentypen;
with KartengrundDatentypen;
with ProduktionDatentypen;

package ArbeitszeitRodenLogik is

   type ArbeitszeitArray is array (RassenDatentypen.Rassen_Verwendet_Enum'Range, KartengrundDatentypen.Kartengrund_Arbeitszeit_Enum'Range) of ProduktionDatentypen.ArbeitszeitVorhanden;
   Arbeitszeit : constant ArbeitszeitArray := (
                                               RassenDatentypen.Menschen_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Kasrodiah_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Lasupin_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Lamustra_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,

                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Manuky_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Suroka_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Pryolon_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Moru_Phisihl_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Larinos_Lotaris_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Carupex_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Alary_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Natries_Zermanis_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Tridatus_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Senelari_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Aspari_2_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Ekropa_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Tesorahn_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 ),

                                               RassenDatentypen.Talbidahr_Enum =>
                                                 (
                                                  KartengrundDatentypen.Eis_Enum            => 5,
                                                  KartengrundDatentypen.Wasser_Enum         => 5,
                                                  KartengrundDatentypen.Küstengewässer_Enum => 2,
                                                  KartengrundDatentypen.Flachland_Enum      => 2,
                                                  KartengrundDatentypen.Wüste_Enum          => 5,
                                                  KartengrundDatentypen.Hügel_Enum          => 3,
                                                  KartengrundDatentypen.Gebirge_Enum        => 5,
                                                  KartengrundDatentypen.Tundra_Enum         => 3,
                                                  KartengrundDatentypen.Wald_Enum           => 3,
                                                  KartengrundDatentypen.Dschungel_Enum      => 3,
                                                  KartengrundDatentypen.Sumpf_Enum          => 3,
                                                  KartengrundDatentypen.Untereis_Enum       => 5,
                                                  KartengrundDatentypen.Küstengrund_Enum    => 2,
                                                  KartengrundDatentypen.Meeresgrund_Enum    => 2,
                                                  KartengrundDatentypen.Korallen_Enum       => 3,
                                                  KartengrundDatentypen.Unterwald_Enum      => 3,
                                                  KartengrundDatentypen.Erde_Enum           => 2,
                                                  KartengrundDatentypen.Erdgestein_Enum     => 2,
                                                  KartengrundDatentypen.Sand_Enum           => 2,
                                                  KartengrundDatentypen.Gestein_Enum        => 5,
                                                  KartengrundDatentypen.Lava_Enum           => 100,
                                                  KartengrundDatentypen.Planetenkern_Enum   => 100,
                                                  KartengrundDatentypen.Ringwoodit_Enum     => 2,
                                                  KartengrundDatentypen.Majorit_Enum        => 2,
                                                  KartengrundDatentypen.Perowskit_Enum      => 2,
                                                  KartengrundDatentypen.Magnesiowüstit_Enum => 2
                                                 )
                                              );

end ArbeitszeitRodenLogik;
