pragma SPARK_Mode (On);

with GlobaleDatentypen, EinheitStadtRecords, EinheitenKonstanten;

with DatenbankRecords;

package EinheitenMoruPhisihl is

   EinheitenMoruPhisihlListe : constant DatenbankRecords.EinheitenListeArray :=
     (
      -- Siedler
      1 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 10,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 3,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 0,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Steinzeitkämpfer
      2 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 5,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Bogenschütze
      3 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 1,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 8,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
      
      -- Erstes Schiff
      4 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 7,
         Passierbarkeit          => (GlobaleDatentypen.Wasser       => True,
                                       -- Für das erste Schiff keine Wasserpassierbarkeit?
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 10,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Bronzekämpfer
      5 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 10,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 6,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Eisenkämpfer
      6 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 13,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 12,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Streitwagen
      7 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 5,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 17,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Katapult
      8 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 11,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 9,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Balliste
      9 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 12,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 13,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Segelschiff
      10 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 14,
         Passierbarkeit          => (GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 11,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Großes Segelschiff
      11 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 23,
         Passierbarkeit          => (GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 14,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Gewehrkämpfer
      12 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 28,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 44,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Kanone
      13 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 34,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 40,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Dampfschiff
      14 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 31,
         Passierbarkeit          => (GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 15,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Motorschiff
      15 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 38,
         Passierbarkeit          => (GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 42,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- U-Boot
      16 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 39,
         Passierbarkeit          => (GlobaleDatentypen.Wasser            => True,
                                     GlobaleDatentypen.Küstenwasser      => True,
                                     GlobaleDatentypen.Unterwasser       => True,
                                     GlobaleDatentypen.Unterküstenwasser => True,
                                     others                              => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 42,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Gepanzerter Wagen
      17 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 40,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 18,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Panzer
      18 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 42,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 35,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Jäger
      19 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 41,
         Passierbarkeit          => (GlobaleDatentypen.Luft => True,
                                     others                 => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 22,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Bomber
      20 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 41,
         Passierbarkeit          => (GlobaleDatentypen.Luft => True,
                                     others                 => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 23,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Rakete
      21 =>
        (EinheitenGrafik         => 'O',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 46,
         Passierbarkeit          => (GlobaleDatentypen.Luft     => True,
                                     GlobaleDatentypen.Weltraum => True,
                                     others                     => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Düsenjäger
      22 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 51,
         Passierbarkeit          => (GlobaleDatentypen.Luft => True,
                                     others                 => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 38,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Düsenbomber
      23 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 51,
         Passierbarkeit          => (GlobaleDatentypen.Luft => True,
                                     others                 => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 39,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Atombombe
      24 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 45,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Drohne
      25 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 49,
         Passierbarkeit          => (GlobaleDatentypen.Luft => True,
                                     others                 => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Gensoldat
      26 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 56,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 28,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Wassersiedler
      27 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 58,
         Passierbarkeit          => (GlobaleDatentypen.Boden        => True,
                                     GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Cyborg
      28 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 57,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 33,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Unterwasser/Unterirdischer Siedler
      29 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 62,
         Passierbarkeit          => (GlobaleDatentypen.Boden             => True,
                                     GlobaleDatentypen.Wasser            => True,
                                     GlobaleDatentypen.Küstenwasser      => True,
                                     GlobaleDatentypen.Unterwasser       => True,
                                     GlobaleDatentypen.Unterküstenwasser => True,
                                     GlobaleDatentypen.Unterirdisch      => True,
                                     others                              => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- PZB20
      30 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Sonstiges,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 63,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- PZB40
      31 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Sonstiges,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 66,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- PZB100
      32 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Sonstiges,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 66,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Gaußkämpfer
      33 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 68,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 34,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Magnetkämpfer
      34 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 74,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Schwebepanzer
      35 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 74,
         Passierbarkeit          => (GlobaleDatentypen.Boden        => True,
                                     GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Planetenkernsiedler
      36 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 65,
         Passierbarkeit          => (GlobaleDatentypen.Boden             => True,
                                     GlobaleDatentypen.Wasser            => True,
                                     GlobaleDatentypen.Küstenwasser      => True,
                                     GlobaleDatentypen.Unterwasser       => True,
                                     GlobaleDatentypen.Unterküstenwasser => True,
                                     GlobaleDatentypen.Unterirdisch      => True,
                                     GlobaleDatentypen.Lava              => True,
                                     GlobaleDatentypen.Planeteninneres   => True,
                                     others                              => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Himmel/Orbitalsiedler
      37 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 72,
         Passierbarkeit          => (GlobaleDatentypen.Boden        => True,
                                     GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     GlobaleDatentypen.Luft         => True,
                                     GlobaleDatentypen.Weltraum     => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Atmosphärenjäger
      38 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 74,
         Passierbarkeit          => (GlobaleDatentypen.Luft     => True,
                                     GlobaleDatentypen.Weltraum => True,
                                     others                     => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Atmosphärenbomber
      39 =>
        (EinheitenGrafik         => 'L',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 74,
         Passierbarkeit          => (GlobaleDatentypen.Luft     => True,
                                     GlobaleDatentypen.Weltraum => True,
                                     others                     => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Artillerie
      40 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 42,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 41,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Stellare Artillerie
      41 =>
        (EinheitenGrafik         => 'F',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 74,
         Passierbarkeit          => (GlobaleDatentypen.Boden        => True,
                                     GlobaleDatentypen.Wasser       => True,
                                     GlobaleDatentypen.Küstenwasser => True,
                                     others                         => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Gräberschiff
      42 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 62,
         Passierbarkeit          => (GlobaleDatentypen.Boden             => True,
                                     GlobaleDatentypen.Wasser            => True,
                                     GlobaleDatentypen.Küstenwasser      => True,
                                     GlobaleDatentypen.Unterwasser       => True,
                                     GlobaleDatentypen.Unterküstenwasser => True,
                                     GlobaleDatentypen.Unterirdisch      => True,
                                     others                              => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 43,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Kerngräber
      43 =>
        (EinheitenGrafik         => 'W',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 65,
         Passierbarkeit          => (GlobaleDatentypen.Boden             => True,
                                     GlobaleDatentypen.Wasser            => True,
                                     GlobaleDatentypen.Küstenwasser      => True,
                                     GlobaleDatentypen.Unterwasser       => True,
                                     GlobaleDatentypen.Unterküstenwasser => True,
                                     GlobaleDatentypen.Unterirdisch      => True,
                                     GlobaleDatentypen.Lava              => True,
                                     GlobaleDatentypen.Planeteninneres   => True,
                                     others                              => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Moderne Infanterie
      44 =>
        (EinheitenGrafik         => 'N',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 40,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 26,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 2,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Alleskönner
      45 =>
        (EinheitenGrafik         => 'A',
         EinheitArt              => GlobaleDatentypen.Beides,
         PreisGeld               => 1,
         PreisRessourcen         => 1,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (others => True),
         MaximaleLebenspunkte    => 100,
         MaximaleBewegungspunkte => 100.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 1,
         MaximalerRang           => 100,
         Reichweite              => 100,
         Angriff                 => 100,
         Verteidigung            => 100,
         KannTransportieren      => 10,
         KannTransportiertWerden => 0,
         Transportkapazität      => EinheitStadtRecords.TransporterArray'Last),
                                                               
      others => EinheitenKonstanten.LeerEinheitListe
     );

end EinheitenMoruPhisihl;
