pragma SPARK_Mode (On);

with GlobaleDatentypen, GlobaleKonstanten, GlobaleRecords;

with DatenbankRecords;

package EinheitenTridatus is

   EinheitenTridatusListe : constant DatenbankRecords.EinheitenListeArray :=
     (
      -- Siedler
      1 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Arbeiter,
         PreisGeld               => 10,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 3,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 1,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Steinbeilkämpfer
      2 =>
        (EinheitenGrafik         => 'C',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Bogenschütze
      3 =>
        (EinheitenGrafik         => 'B',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 25,
         PreisRessourcen         => 20,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 5,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 5,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 4,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 3,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Kanone
      4 =>
        (EinheitenGrafik         => 'K',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 50,
         PreisRessourcen         => 5,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 8,
         Passierbarkeit          => (GlobaleDatentypen.Boden => True,
                                     others                  => False),
         MaximaleLebenspunkte    => 3,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 3,
         Angriff                 => 8,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 2,
         Transportkapazität      => 0),
                                               
      -- Ägyptisches Nilschiff
      5 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 20,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Wasser => True,
                                     others                   => False),
         MaximaleLebenspunkte    => 2,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 1,
         Verteidigung            => 1,
         KannTransportieren      => 2,
         KannTransportiertWerden => 0,
         Transportkapazität      => 2),
                                               
      -- Kanonenschiff
      6 =>
        (EinheitenGrafik         => 'S',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 20,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 20,
         Passierbarkeit          => (GlobaleDatentypen.Wasser => True,
                                     others                   => False),
         MaximaleLebenspunkte    => 3,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 8,
         Verteidigung            => 1,
         KannTransportieren      => 2,
         KannTransportiertWerden => 0,
         Transportkapazität      => 0),
                                               
      -- UBoot
      7 =>
        (EinheitenGrafik         => 'U',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 20,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 20,
         Passierbarkeit          => (GlobaleDatentypen.Wasser      => True,
                                     GlobaleDatentypen.Unterwasser => True,
                                     others                        => False),
         MaximaleLebenspunkte    => 1000,
         MaximaleBewegungspunkte => 100.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 10,
         Verteidigung            => 10,
         KannTransportieren      => 0,
         KannTransportiertWerden => 0,
         Transportkapazität      => 5),
                                               
      -- Jäger
      8 =>
        (EinheitenGrafik         => 'J',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 100,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 20,
         Passierbarkeit          => (GlobaleDatentypen.Boden  => True,
                                     GlobaleDatentypen.Wasser => True,
                                     GlobaleDatentypen.Luft   => True,
                                     others                   => False),
         MaximaleLebenspunkte    => 8,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 10,
         Verteidigung            => 1,
         KannTransportieren      => 0,
         KannTransportiertWerden => 1,
         Transportkapazität      => 0),
                                               
      -- Bomber
      9 =>
        (EinheitenGrafik         => 'B',
         EinheitArt              => GlobaleDatentypen.Fernkämpfer,
         PreisGeld               => 100,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (GlobaleDatentypen.Boden  => True,
                                     GlobaleDatentypen.Wasser => True,
                                     GlobaleDatentypen.Luft   => True,
                                     others                   => False),
         MaximaleLebenspunkte    => 8,
         MaximaleBewegungspunkte => 3.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 10,
         Verteidigung            => 1,
         KannTransportieren      => 2,
         KannTransportiertWerden => 0,
         Transportkapazität      => 0),
                                               
      -- Rakete
      10 =>
        (EinheitenGrafik         => 'R',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 20,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 20,
         Passierbarkeit          => (GlobaleDatentypen.Boden    => True,
                                     GlobaleDatentypen.Wasser   => True,
                                     GlobaleDatentypen.Luft     => True,
                                     GlobaleDatentypen.Weltraum => True,
                                     others                     => False),
         MaximaleLebenspunkte    => 1000,
         MaximaleBewegungspunkte => 100.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 10,
         Verteidigung            => 10,
         KannTransportieren      => 0,
         KannTransportiertWerden => 0,
         Transportkapazität      => 0),
                                               
      -- Unterwasserrakete
      11 =>
        (EinheitenGrafik         => 'R',
         EinheitArt              => GlobaleDatentypen.Nahkämpfer,
         PreisGeld               => 20,
         PreisRessourcen         => 10,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 20,
         Passierbarkeit          => (GlobaleDatentypen.Boden       => True,
                                     GlobaleDatentypen.Wasser      => True,
                                     GlobaleDatentypen.Luft        => True,
                                     GlobaleDatentypen.Weltraum    => True,
                                     GlobaleDatentypen.Unterwasser => True,
                                     others                        => False),
         MaximaleLebenspunkte    => 1000,
         MaximaleBewegungspunkte => 100.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 30,
         MaximalerRang           => 3,
         Reichweite              => 1,
         Angriff                 => 10,
         Verteidigung            => 10,
         KannTransportieren      => 0,
         KannTransportiertWerden => 0,
         Transportkapazität      => 0),
                                               
      -- Alleskönner
      12 =>
        (EinheitenGrafik         => 'A',
         EinheitArt              => GlobaleDatentypen.Beides,
         PreisGeld               => 1,
         PreisRessourcen         => 1,
         PermanenteKosten        => (others => 0),
         Anforderungen           => 0,
         Passierbarkeit          => (others => True),
         MaximaleLebenspunkte    => 100,
         MaximaleBewegungspunkte => 100.00,
         WirdVerbessertZu        => 0,
         Beförderungsgrenze      => 1,
         MaximalerRang           => 1,
         Reichweite              => 1,
         Angriff                 => 1,
         Verteidigung            => 1,
         KannTransportieren      => 10,
         KannTransportiertWerden => 0,
         Transportkapazität      => GlobaleRecords.TransporterArray'Last),
                                                               
      others => GlobaleKonstanten.LeerEinheitListe
     );

end EinheitenTridatus;
