--  Configuration for honki_tonks_zivilisationen generated by Alire
pragma Restrictions (No_Elaboration_Code);

package Honki_Tonks_Zivilisationen_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "honki_tonks_zivilisationen";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "debian";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Honki_Tonks_Zivilisationen_Config;
