RassenDatentypen.Menschen_Enum         => ,
  RassenDatentypen.Kasrodiah_Enum        => ,
    RassenDatentypen.Lasupin_Enum          => ,
      RassenDatentypen.Lamustra_Enum         => ,
        RassenDatentypen.Manuky_Enum           => ,
          RassenDatentypen.Suroka_Enum           => ,
            RassenDatentypen.Pryolon_Enum          => ,
              RassenDatentypen.Moru_Phisihl_Enum     => ,
                RassenDatentypen.Larinos_Lotaris_Enum  => ,
                  RassenDatentypen.Carupex_Enum          => ,
                    RassenDatentypen.Alary_Enum            => ,
                      RassenDatentypen.Natries_Zermanis_Enum => ,
                        RassenDatentypen.Tridatus_Enum         => ,
                          RassenDatentypen.Senelari_Enum         => ,
                            RassenDatentypen.Aspari_2_Enum         => ,
                              RassenDatentypen.Ekropa_Enum           => ,
                                RassenDatentypen.Tesorahn_Enum         => ,
                                  RassenDatentypen.Talbidahr_Enum        =>



Menschen => bevorzugten Lebensräume sind Regionen mit gemäßigtem oder warmem Klima
Kasrodiah => in der Nähe fliesender Gewässer oder seichter Küstengebiete, innerhalb eines Klimas welches die permanenz des Wasser gewährleistet
Lasupin => allen Landklimazonen gleichmäßig vertreten
Lamustra => am liebsten in der Nähe fliesender Gewässer oder seichter Küstenregionen, allerdings haben sie keine Probleme mit kalten Regionen, in welchen das Wasser vorübergehen gefroren ist.
Manuky => Waldgebiete in gemäßigtem und kaltem Klima
Suroka => abgesehen von Wüsten und Eisgebieten, in allen Klimazonen
Pryolon => bevorzugt in Wäldern, Steppen und Bergregionen
Moru_Phisihl => alle Gebiete ohne Dschungel, Wüsten oder Sümpfe
Larinos_Lotaris => allen Klimazonen
Carupex => hohe Gebirge und höher gelegenes Flachland
Alary => emäßigten und warmen Regionen, aber niemals in dichten Wäldern
Natries_Zermanis => allen Landgebieten
Tridatus => Sümpfe oder Wälder in Fluss- und Küstennähe
Senelari => gemäßigtem und warmen Klima an Land
Aspari_2 => Alle Umgebungen auf denen Maschinen existieren können
Ekropa => bevorzugen bewaldete Flächen in gemäßigtem oder warmen Klima
Tesorahn => bevorzugter Lebensraum sind Salzgewässer in flüssigem Zustand
Talbidahr => Unterirdisch in gemäßigten Klimazonen
